# Generated by Django 3.0.2 on 2020-01-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mascota', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=25)),
                ('raza', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('en_adopcion', models.BooleanField(default=False)),
                ('esta_perdida', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Usuario')),
            ],
        ),
    ]
